# Site settings
title: Dogec0in
email: sgcookiemonster92@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
        Very currency, wow
baseurl: "/dogec0in" # the subpath of your site, e.g. /blog/
url: "http://schaafhirtin.github.io" # the base hostname & protocol for your site
twitter_username: schaafhirtin 
github_username:  schaafhirtin

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
