# Site settings
title: Dogec0in
email: sgcookiemonster92@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dogec0in" # the subpath of your site, e.g. /blog/
url: "http://schaafhirtin.github.io" # the base hostname & protocol for your site
twitter_username: schaafhirtin 
github_username:  schaafhirtin

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
